### PR TITLE
Gradio Web Demo

### PR DESCRIPTION
**Pull request by AK391**
easy to use web demo on gradio hub

### CODE REVIEW

**Comment by AK391** [comment]
@mchong6 thanks for merging!, can you use this link instead of the current link https://gradio.app/hub/AK391/GANsNRoses to the demo
and if you want can add this image in the readme :)
Screen Shot 2021-06-17 at 10 21 27 AM

**Comment by mchong6** [comment]
done :)

**Comment by AK391** [comment]
@mchong6 thank you! is there a way to randomly pick the style, currently I have it set to one style or let the user pick the style?

**Comment by AK391** [comment]
@mchong6 I see i can change the seed        
 torch.manual_seed(random.randint(1, 100000)) 
and choose a random int instead of the hardcoded 
torch.manual_seed(84986)
but even after I run this it chooses the same style after every run

**Comment by mchong6** [comment]
This is the line that produces the style https://github.com/mchong6/GANsNRoses/blob/b031590266c6f2b0401794149c23ee8f3797a103/gradiodemo.py#L54

I am assuming that the style will change if you move this line into the inference function? So every time the inference function gets called, a new style gets sampled.

**Comment by AK391** [comment]
@mchong6 thank you again! I made the change and the demo can now do multiple styles. looks great!
Screen Shot 2021-06-19 at 1 18 39 AM

**Comment by AK391** [comment]
although sometimes it gives artifacts overall great though
Screen Shot 2021-06-19 at 1 22 16 AM

**Comment by mchong6** [comment]
It was trained on quite a small dataset. So potentially it could be better if trained on a bigger one :)

**Comment by mchong6** [comment]
I added a snippet of code on colab that lets you upload an image and it will automatically crop and frame the image. For more consistent results, maybe you could consider doing that on gradio?

**Comment by AK391** [comment]
@mchong6 ok thanks saw the issue with face cropping as well, also congrats on being at the top of ml reddit!, I am thinking of using autocrop instead of dlib for the demo https://github.com/leblancfg/autocrop as dlib has issues with pip

**Comment by mchong6** [comment]
I have you to thank for that! I looked at autocrop, it will be a good option for cropping images. Unfortunately, it doesn't return the bounding box coordinates, so I cant use it for cropping faces of videos.

**Comment by AK391** [comment]
@mchong6 no problem, thanks for the great paper, yeah sucks it doesnt work for video for autocrop. I just tested it in colab now will add it to live demo
Screen Shot 2021-06-19 at 1 25 50 PM

**Comment by mchong6** [comment]
Might work a little better if the face is a little more zoomed in. Autocrop has an argument face_percent that can do that.

**Comment by AK391** [comment]
@mchong6 ah ok, the default face_percent is set to 50, do you think it should be a higher like 70?

**Comment by mchong6** [comment]
I don't have that set up to test right now but that does sound reasonable.

**Comment by mchong6** [comment]
@AK391 i was playing with the gradio demo and realize sometimes there are color artifacts. The reason is that the image is not [0, 255] when it is saved. To fix that, at this line
https://github.com/AK391/GANsNRoses/blob/55516baab26e802b9fa2131c558e31e6418f3a34/gradiodemo.py#L75
you need to change
`
fake_A2B = G_A2B.decode(A2B_content.repeat(num_styles,1,1,1), style).clamp(-1,1)
`

**Pull request merged**
